version: 3
services:
  app:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: docker.io/postgres:16.0
    restart: always
    ports:
      - 5432:5432
    networks:
      - postgres-network
    env_file:
      - .env
    volumes:
      - /tmp/db/:/var/lib/postgresql/data/

networks:
  postgres-network:
    driver: bridge
