version: "3"

services:
  app:
    build: .
    ports:
      - "${USERS_API_PORT-8000}:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - db-network
  db:
    image: postgres:16.0
    restart: always
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname $${POSTGRES_DB} --host=$${POSTGRES_ADDR} --port=$${POSTGRES_PORT} --username=$${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - db-network
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data/

networks:
  db-network:
    driver: bridge

volumes:
  db-data:
    driver: local
